const socketEvents = {
    JOIN_ROOM: 'JOIN_ROOM',
    JOIN_MULTIPLE_ROOMS: 'JOIN_MULTIPLE_ROOMS',
    INBOX: 'INBOX',
    RECEIVE_MESSAGE: 'RECEIVE_MESSAGE',
    NEW_MESSAGE: 'NEW_MESSAGE',
    NEW_CHAT: 'NEW_CHAT',
    DELETE_CHAT: 'DELETE_CHAT',
    DELETE_MESSAGE: 'DELETE_MESSAGE',
    REACT_MESSAGE: 'REACT_MESSAGE',
    REMOVE_REACTION: 'REMOVE_REACTION'
};

module.exports = socketEvents